const states = [
  { state: "Alabama", abbv: "AL" },
  { state: "Alaska", abbv: "AK" },
  { state: "Arizona", abbv: "AZ" },
  { state: "Arkansas", abbv: "AR" },
  { state: "California", abbv: "CA" },
  { state: "Colorado", abbv: "CO" },
  { state: "Connecticut", abbv: "CT" },
  { state: "Delaware", abbv: "DE" },
  { state: "Florida", abbv: "FL" },
  { state: "Georgia", abbv: "GA" },
  { state: "Hawaii", abbv: "HI" },
  { state: "Idaho", abbv: "ID" },
  { state: "Illinois", abbv: "IL" },
  { state: "Indiana", abbv: "IN" },
  { state: "Iowa", abbv: "IA" },
  { state: "Kansas", abbv: "KS" },
  { state: "Kentucky", abbv: "KY" },
  { state: "Louisiana", abbv: "LA" },
  { state: "Maine", abbv: "ME" },
  { state: "Maryland", abbv: "MD" },
  { state: "Massachusetts", abbv: "MA" },
  { state: "Michigan", abbv: "MI" },
  { state: "Minnesota", abbv: "MN" },
  { state: "Mississippi", abbv: "MS" },
  { state: "Missouri", abbv: "MO" },
  { state: "Montana", abbv: "MT" },
  { state: "Nebraska", abbv: "NE" },
  { state: "Nevada", abbv: "NV" },
  { state: "New Hampshire", abbv: "NH" },
  { state: "New Jersey", abbv: "NJ" },
  { state: "New Mexico", abbv: "NM" },
  { state: "New York", abbv: "NY" },
  { state: "North Carolina", abbv: "NC" },
  { state: "North Dakota", abbv: "ND" },
  { state: "Ohio", abbv: "OH" },
  { state: "Oklahoma", abbv: "OK" },
  { state: "Oregon", abbv: "OR" },
  { state: "Pennsylvania", abbv: "PA" },
  { state: "Rhode Island", abbv: "RI" },
  { state: "South Carolina", abbv: "SC" },
  { state: "South Dakota", abbv: "SD" },
  { state: "Tennessee", abbv: "TN" },
  { state: "Texas", abbv: "TX" },
  { state: "Utah", abbv: "UT" },
  { state: "Vermont", abbv: "VT" },
  { state: "Virginia", abbv: "VA" },
  { state: "Washington", abbv: "WA" },
  { state: "West Virginia", abbv: "WV" },
  { state: "Wisconsin", abbv: "WI" },
  { state: "Wyoming", abbv: "WY" },
];

export default states;
